### PR TITLE
Chapter 1 Correction

### PR DESCRIPTION
**Pull request by leafy-lee**
Fix some typos
Global minimum is local minimum
Taylor's Formula needs an interval
Counterexample: 
$$y=exp(-\frac{1}{x^2}),\quad x\neq0 \quad\quad$$
$$y = 0, x=0$$
 can only be decomposition at x = 0

### CODE REVIEW

**Comment by AmourWaltz** [comment]
> Fix some typos Global minimum is local minimum Taylor's Formula needs an interval Counterexample: y=exp(−1x2),x≠0 y=0,x=0 can only be decomposition at x = 0

Thanks for pointing out the typos

**Comment by leafy-lee** [comment]
You can directly merge it into your repo since it has no confilicts with the base branch.

**Comment by AmourWaltz** [comment]
> You can directly merge it into your repo since it has no confilicts with the base branch.

Thank you. Sorry that I'm suffering from Covid-19 these days. Could I have your WeChat for further communications?

**Comment by leafy-lee** [comment]
That must be tough, feel sorry to hear about that. My WeChat ID is  leafy-lee.
________________________________
发件人: AmourWaltz ***@***.***>
发送时间: 2022年12月28日 18:27
收件人: AmourWaltz/Dive-into-PRML ***@***.***>
抄送: YiFei Li ***@***.***>; Author ***@***.***>
主题: Re: [AmourWaltz/Dive-into-PRML] Chapter 1 Correction (PR #1)


You can directly merge it into your repo since it has no confilicts with the base branch.

Thank you. Sorry that I'm suffering from Covid-19 these days. Could I have your WeChat for further communications?

―

**Pull request merged**
